### ISSUE TITLE
Why aren't these mask images binary?

### ISSUE THREAD

**Issue by yyywxk** [nie-lang/DeepRectangling#5]
I found these mask images were not composed of 0 and 255 when I used `cv2.imread` to input them.  So why not use binary images as mask images?

**Comment by nie-lang** [comment]
I have checked the dataset after seeing this issue. There are other pixel values (except 0 and 255) near the boundaries. Your suggestion would be more reasonable, but it would require extensive human efforts to correct them.

From my experience, it makes little difference in the performance even using binary images. Furthermore, even without the mask, the network can be trained successfully. In my view, the network predicts the initial mesh according to the input image rather than the mask.

**Comment by yyywxk** [comment]
ok, thank you!
